### ISSUE TITLE
Expose all versions of crates that have been compiled

### ISSUE THREAD

**Issue by shepmaster** [integer32llc/rust-playground#532]
Newer Cargo versions allow renaming. Instead of exposing only the unique crates by newest version, we could rename the older versions (and maybe *also* rename the newer ones for consistency?).

Something like:

```toml
rand = { version = "=0.7.0" }
rand_0_7_0 = { version = "=0.7.0", package = "rand" }
rand_0_6_5 = { version = "=0.6.5", package = "rand" }
```

We'd also have to make sure that the JSON file for the frontend data can handle that.
